### ISSUE TITLE
Does not work with Geth Classic

### ISSUE THREAD

**Issue by soc1c** [ChainSafe/Anemone#13]
```
(node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockNumber' of null
    at resolve (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:39:20)
    at new Promise (<anonymous>)
    at transactionRecieptExist (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:38:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:26047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:26047) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockNumber' of null
    at resolve (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:39:20)
    at new Promise (<anonymous>)
    at transactionRecieptExist (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:38:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:26047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockNumber' of null
    at resolve (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:39:20)
    at new Promise (<anonymous>)
    at transactionRecieptExist (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:38:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:26047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockNumber' of null
    at resolve (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:39:20)
    at new Promise (<anonymous>)
    at transactionRecieptExist (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:38:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:26047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockNumber' of null
    at resolve (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:39:20)
    at new Promise (<anonymous>)
    at transactionRecieptExist (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:38:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:26047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
(node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockNumber' of null
    at resolve (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:39:20)
    at new Promise (<anonymous>)
    at transactionRecieptExist (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:38:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:26047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockNumber' of null
    at resolve (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:39:20)
    at new Promise (<anonymous>)
    at transactionRecieptExist (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:38:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:26047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockNumber' of null
    at resolve (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:39:20)
    at new Promise (<anonymous>)
    at transactionRecieptExist (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:38:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:26047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
(node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockNumber' of null
    at resolve (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:39:20)
    at new Promise (<anonymous>)
    at transactionRecieptExist (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:38:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:26047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
(node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockNumber' of null
    at resolve (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:39:20)
    at new Promise (<anonymous>)
    at transactionRecieptExist (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:38:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:26047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
(node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockNumber' of null
    at resolve (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:39:20)
    at new Promise (<anonymous>)
    at transactionRecieptExist (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:38:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:26047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
(node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockNumber' of null
    at resolve (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:39:20)
    at new Promise (<anonymous>)
    at transactionRecieptExist (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:38:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:26047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
(node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockNumber' of null
    at resolve (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:39:20)
    at new Promise (<anonymous>)
    at transactionRecieptExist (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:38:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:26047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
(node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockNumber' of null
    at resolve (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:39:20)
    at new Promise (<anonymous>)
    at transactionRecieptExist (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:38:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:26047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
(node:26047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockNumber' of null
    at resolve (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:39:20)
    at new Promise (<anonymous>)
    at transactionRecieptExist (/home/user/.opt/Anemone/lib/utilities/isTransactionMined.js:38:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:26047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
Done in 25.19s.
```

**Comment by soc1c** [comment]
Tested against Geth Classic 6.0.9 on Nazgul

Works with Multi-Geth 1.9.2 on Nazgul

**Comment by GregTheGreek** [comment]
is --rpc enabled on gethclassic?

**Comment by soc1c** [comment]
Yep

**Comment by steviezhang** [comment]
Can't reproduce, works fine w/ the Geth Classic 6.0.9 release on my machine, can you provide more context?

**Comment by steviezhang** [comment]
@soc1c were you able to reproduce?

**Comment by soc1c** [comment]
No, I can't reproduce this rn
