### ISSUE TITLE
Error: replacement fee too low

### ISSUE THREAD

**Issue by soc1c** [ChainSafe/Anemone#14]
```
transaction mined! (hash: 0xbbc54dd8eb23811325e873f41385ed844efa73fda6e030a8d1cb134b7874168c)


calling testOpcodes...
Anemone executed with errors:  { Error: replacement fee too low (version=4.0.33)
    at Object.throwError (/home/user/.opt/Anemone/node_modules/ethers/errors.js:76:17)
    at /home/user/.opt/Anemone/node_modules/ethers/providers/json-rpc-provider.js:284:36
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  reason: 'replacement fee too low',
  code: 'REPLACEMENT_UNDERPRICED',
  transaction:
   { nonce: 52,
     gasPrice: BigNumber { _hex: '0x09c7652400' },
     gasLimit: BigNumber { _hex: '0x231860' },
     to: '0x61792B7bB39b2C359660Ed1082154c1daf7fc96a',
     value: BigNumber { _hex: '0x00' },
     data: '0x391521f4',
     chainId: 1447,
     v: 2930,
     r:
      '0x247c77fbd2d35a80ca10fdf26f247e7d39cdf9bd3388a2623ff43206318674b7',
     s:
      '0x5965a3911c08a11c463ef2b67571eeeb2d68fe263ca01c90e63c1407f56e09b9',
     from: '0x00D5842976C0D35d511dAE0A36f9a2C9368Ee8b0',
     hash:
      '0x8e82bd328cc16e79c600ea2dc54dac9ec65b914d17086e753a0466eb1dee5d97' },
  transactionHash:
   '0x8e82bd328cc16e79c600ea2dc54dac9ec65b914d17086e753a0466eb1dee5d97' }
Done in 75.59s.
```

**Comment by soc1c** [comment]
Config

```

const config = {

  //Url to node open for RPC, defaults to default localhost port
  rpcUrl: "http://163.172.154.197:8545",

  //number of transactions to generate and throw
  numTransactions: "50",

  //number of wallets that will be created to throw/recieve transactions
  numWallets: "50",

  //set true to deploy and test the smart contracts containing each opcode
  testOpCodes: true,

  //set true to deploy and test the smart contracts containing edgecases we have run into
  testEdgecases: true,

  //value (in wei) to send in each transation
  amount: "1000000000000000",

  //gas price in gwei for each transaction generated
  gasPrice: "42",

  //max gas to set for each transaction generated
  maxGas: "2300000",

  //chainId, currently 1337 for kensignton testnet
  chainId: 1447,

};
```

Multi-Geth 1.9.2 on Nazgul

**Comment by GregTheGreek** [comment]
@steviezhang are we expecting to do a same nonce tx?

**Comment by steviezhang** [comment]
> @steviezhang are we expecting to do a same nonce tx?

No we aren't. I also can't reproduce this with the config and Multi-Geth 1.9.2 on Nazgul, is there any more context you can provide @soc1c?

**Comment by steviezhang** [comment]
@soc1c were you able to reproduce?

**Comment by soc1c** [comment]
No, I can't reproduce this rn
