### ISSUE TITLE
 Error: underflow (operation="setValue", fault="underflow", value=204.8, outputValue=204

### ISSUE THREAD

**Issue by soc1c** [ChainSafe/Anemone#15]
```
Created wallet with address 0x2CfD2668d8b743599b05a14d2696381b2b183D3c


Anemone executed with errors:  { Error: underflow (operation="setValue", fault="underflow", value=204.8, outputValue=204, version=4.0.33)
    at Object.throwError (/home/user/.opt/Anemone/node_modules/ethers/errors.js:76:17)
    at new BigNumber (/home/user/.opt/Anemone/node_modules/ethers/utils/bignumber.js:77:24)
    at Object.bigNumberify (/home/user/.opt/Anemone/node_modules/ethers/utils/bignumber.js:182:12)
    at bn (/home/user/.opt/Anemone/lib/utilities/conversion.js:16:23)
    at fundWallets (/home/user/.opt/Anemone/lib/anemone.js:49:46)
    at Main (/home/user/.opt/Anemone/lib/index.js:49:51)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:52:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
  reason: 'underflow',
  code: 'NUMERIC_FAULT',
  operation: 'setValue',
  fault: 'underflow',
  value: 204.8,
  outputValue: 204 }
Done in 2.19s.
```

**Comment by soc1c** [comment]
Config

```
const config = {

  //Url to node open for RPC, defaults to default localhost port
  rpcUrl: "http://163.172.154.197:9545",

  //number of transactions to generate and throw
  numTransactions: "1024",

  //number of wallets that will be created to throw/recieve transactions
  numWallets: "5",

  //set true to deploy and test the smart contracts containing each opcode
  testOpCodes: true,

  //set true to deploy and test the smart contracts containing edgecases we have run into
  testEdgecases: true,

  //value (in wei) to send in each transation
  amount: "1000000000000000",

  //gas price in gwei for each transaction generated
  gasPrice: "42",

  //max gas to set for each transaction generated
  maxGas: "2300000",

  //chainId, currently 1337 for kensignton testnet
  chainId: 1447,

};
```

Connected to Multi-Geth 1.9.2 on Nazgul
